apiVersion: apps/v1
kind: Deployment
metadata: 
  name: phpanalyser
  labels:
    app: phpanalyser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpanalyser
  template:
    metadata:
      labels:
        app: phpanalyser
    spec:
      containers:
      - name: phpanalyser
        image: phpanalyser:0.2
        ports:
        - containerPort: 80

---
